/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tab1bit0 (https://sketchfab.com/tab1bit0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/island-in-the-sky-2c90fca65dcc484b8c3084b8eb884672
Title: Island in the sky
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";
import {bkPoint} from "../../../../utils/responsiveness.js";
import {useSelector} from "react-redux";
import {getScene5I} from "../../../../utils/store/utils-store/utils-store-selectors.js";


const Island5 = ({scrollHandler, mesh, ...props}) => {
    const island5Nodes = useSelector(getScene5I)
    const {nodes, materials} = island5Nodes

    const enlargementFactor = .5
    const rotationFactor = 4
    const idleRotationFactor = .2
    let targetScale = .13


    useEffect(() => {
        if(window.innerWidth < bkPoint)
            targetScale = .08
    }, []);

    useFrame((state, delta) => {
        if(mesh.current.scale.x > targetScale)
            mesh.current.scale.x = targetScale
        if(mesh.current.scale.y > targetScale)
            mesh.current.scale.y = targetScale
        if(mesh.current.scale.z > targetScale)
            mesh.current.scale.z = targetScale


        if(mesh.current.scale.x < targetScale)
            mesh.current.scale.x += (enlargementFactor * delta)
        if(mesh.current.scale.y < targetScale)
            mesh.current.scale.y += (enlargementFactor * delta)
        if(mesh.current.scale.z < targetScale)
            mesh.current.scale.z += (enlargementFactor * delta)

        if(mesh.current.rotation.y < -2)
            mesh.current.rotation.y += (rotationFactor * delta)

        mesh.current.rotation.y += (idleRotationFactor * delta)
    })

    useEffect(() => {
        if(!scrollHandler)
            return

        scrollHandler()
    }, [scrollHandler])


    return (
        <group {...props} ref={mesh} dispose={null}>
            <group position={[8.221, 2.393, 8.095]} rotation={[-2.194, 1.091, -2.137]} scale={0.213}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials['Tree.green.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.Tree00}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials.Tree01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials['Tree.green']}
                />
            </group>
            <group position={[-5.446, 5.352, -6.604]} rotation={[0.042, 0.056, -0.244]} scale={0.105}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.Spurce}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials['Spurce.green']}
                />
            </group>
            <group position={[-4.468, 5.018, -7.749]} rotation={[0.247, 0.262, -0.434]} scale={0.07}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials.Spurce}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials['Spurce.green']}
                />
            </group>
            <group
                position={[8.519, 2.104, 5.644]}
                rotation={[-2.706, 0.176, -1.202]}
                scale={[0.149, 0.218, 0.149]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials['Tree.green.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.Tree00}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.Tree01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials['Tree.green']}
                />
            </group>
            <group
                position={[8.937, 2.459, 8.866]}
                rotation={[-0.276, 0.562, 1.987]}
                scale={[0.136, 0.174, 0.127]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials['Tree.green.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.Tree00}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials.Tree01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials['Tree.green']}
                />
            </group>
            <group
                position={[1.509, 2.813, 12.028]}
                rotation={[-0.577, -0.122, 1.767]}
                scale={[0.208, 0.161, 0.186]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={materials['Tree.green.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.Tree00}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.Tree01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials['Tree.green']}
                />
            </group>
            <group
                position={[3.229, 3.074, -9.66]}
                rotation={[0.012, 0.25, -0.508]}
                scale={[0.045, 0.063, 0.045]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials.Spurce}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials['Spurce.green']}
                />
            </group>
            <group
                position={[2.411, 3.676, -9.723]}
                rotation={[-0.029, 0.201, -0.447]}
                scale={[0.051, 0.042, 0.051]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.Spurce}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_38.geometry}
                    material={materials['Spurce.green']}
                />
            </group>
            <group
                position={[2.951, 2.909, -10.768]}
                rotation={[0.101, 0.53, -0.622]}
                scale={[0.029, 0.053, 0.029]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials.Spurce}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_41.geometry}
                    material={materials['Spurce.green']}
                />
            </group>
            <group
                position={[7.535, 1.476, -6.618]}
                rotation={[0.34, 1.2, -0.411]}
                scale={[0.073, 0.069, 0.073]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_43.geometry}
                    material={materials.Spurce}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_44.geometry}
                    material={materials['Spurce.green']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.Ground}
                scale={[12.246, 10, 12.246]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials.Water}
                position={[0, 0.906, 0]}
                scale={19.31}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_46.geometry}
                material={materials.Cloud}
                position={[-12.49, 11.16, 3.032]}
                rotation={[-0.3, -0.851, -0.118]}
                scale={[2.345, 2.091, 2.091]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_48.geometry}
                material={materials.Cloud}
                position={[1.884, 11.482, 13.416]}
                rotation={[-0.059, 0.272, 0.097]}
                scale={1.795}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_50.geometry}
                material={materials.Cloud}
                position={[-2.581, 11.139, -10.959]}
                rotation={[-2.147, -0.946, -2.348]}
                scale={[1.519, 1.354, 1.354]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_52.geometry}
                material={materials.Cloud}
                position={[9.118, 12.014, -11.253]}
                rotation={[-3.107, -0.192, 3.08]}
                scale={[1.423, 0.923, 1.517]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_54.geometry}
                material={materials.Cloud}
                position={[-9.07, 11.651, -8.972]}
                rotation={[-0.216, -0.429, 0.02]}
                scale={1.026}
            />
        </group>
    )
}

useGLTF.preload('../../../assets/models/islands/island_in_the_sky.glb')

export default Island5