/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Niraj (https://sketchfab.com/niraj.upadhyay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-island-8e833807c38848eab52ef93676fec90c
Title: Low poly island
*/

import React, {useEffect, useRef, useState} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";
import {bkPoint} from "../../../../utils/responsiveness.js";
import {useSelector} from "react-redux";
import {getScene3I} from "../../../../utils/store/utils-store/utils-store-selectors.js";
import island3Gltf from "../../../assets/models/islands/low_poly_island (1).glb";

const Island3 = ({scrollHandler, mesh, ...props}) => {
    let island3Nodes = useSelector(getScene3I)

    if(!island3Nodes)
        island3Nodes = useGLTF(island3Gltf)

    const {nodes, materials} = island3Nodes

    const enlargementFactor = .5
    const rotationFactor = 4.5
    const idleRotationFactor = .2
    let targetScale = .2

    useEffect(() => {
        if(window.innerWidth < bkPoint)
            targetScale = .1
    }, []);



    useFrame((state, delta) => {
        if(mesh.current.scale.x > targetScale)
            mesh.current.scale.x = targetScale
        if(mesh.current.scale.y > targetScale)
            mesh.current.scale.y = targetScale
        if(mesh.current.scale.z > targetScale)
            mesh.current.scale.z = targetScale


        if(mesh.current.scale.x < targetScale)
            mesh.current.scale.x += (enlargementFactor * delta)
        if(mesh.current.scale.y < targetScale)
            mesh.current.scale.y += (enlargementFactor * delta)
        if(mesh.current.scale.z < targetScale)
            mesh.current.scale.z += (enlargementFactor * delta)

        if(mesh.current.rotation.y < 2)
            mesh.current.rotation.y += (rotationFactor * delta)

        mesh.current.rotation.y += (idleRotationFactor * delta)
    })

    useEffect(() => {
        if(!scrollHandler)
            return

        scrollHandler()
    }, [scrollHandler])

    return (
        <group {...props} ref={mesh} dispose={null}>
            <group scale={10}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials['Material.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials['Material.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials['Material.012']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.013']}
                />
            </group>
            <group position={[4.562, 1.297, -6.418]} rotation={[0, 0.897, 0]} scale={0.242}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials['Material.004']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials['Material.006']}
                />
            </group>
            <group position={[2.43, 1.964, 7.95]} scale={0.094}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[-7.235, 2.12, 3.368]} scale={0.077}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[3.427, 1.068, 7.577]} scale={0.094}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[1.386, -0.62, -2.823]} rotation={[0, 0.897, 0]} scale={0.242}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials['Material.004']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials['Material.006']}
                />
            </group>
            <group position={[6.46, 1.61, 5.515]} scale={0.112}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[2.43, 1.964, 7.95]} scale={0.094}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[3.427, 1.068, 7.577]} scale={0.094}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[1.386, -0.62, -2.823]} rotation={[0, 0.897, 0]} scale={0.242}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials['Material.004']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials['Material.006']}
                />
            </group>
            <group position={[-7.692, 0.029, 0.877]} scale={0.094}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[-3.766, -0.632, -1.636]} scale={0.094}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_43.geometry}
                    material={materials['Material.007']}
                />
            </group>
            <group position={[-1.073, 0.17, 6.121]} rotation={[-0.347, 1.03, 0.009]} scale={0.242}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_45.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_46.geometry}
                    material={materials['Material.004']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials['Material.006']}
                />
            </group>
            <group position={[-3.288, -0.094, -5.426]} rotation={[-0.45, 1.278, 0.53]} scale={0.242}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_49.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_50.geometry}
                    material={materials['Material.004']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_51.geometry}
                    material={materials['Material.006']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_53.geometry}
                material={materials.Material}
                position={[-1.71, -1.122, 4.027]}
                scale={13.462}
            />
        </group>
    )
}

useGLTF.preload('../../../assets/models/islands/low_poly_island (1).glb')

export default Island3